In [2]:
#numeric without using builtin functions
import numpy as np
import pandas as pd
import os
df=pd.read_csv("numeric.csv")
df

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f609,f610,f611,f612,f613,f614,f615,f616,f617,class
0,-0.4394,-0.0930,0.1718,0.4620,0.6226,0.4704,0.3578,0.0478,-0.1184,-0.2310,...,0.4102,0.2052,0.3846,0.3590,0.5898,0.3334,0.6410,0.5898,-0.4872,'1'
1,-0.4348,-0.1198,0.2474,0.4036,0.5026,0.6328,0.4948,0.0338,-0.0520,-0.1302,...,0.0000,0.2954,0.2046,0.4772,0.0454,0.2046,0.4318,0.4546,-0.0910,'1'
2,-0.2330,0.2124,NaN,0.5222,-0.3422,-0.5840,-0.7168,-0.6342,-0.8614,-0.8318,...,-0.1112,-0.0476,-0.1746,0.0318,-0.0476,0.1112,0.2540,0.1588,-0.4762,'2'
3,-0.3808,-0.0096,0.2602,0.2554,-0.4290,-0.6746,-0.6868,-0.6650,-0.8410,-0.9614,...,-0.0504,-0.0360,-0.1224,0.1366,0.2950,0.0792,-0.0072,0.0936,-0.1510,'2'
4,-0.3412,0.0946,0.6082,0.6216,-0.1622,NaN,-0.4324,-0.4358,-0.4966,-0.5406,...,0.1562,0.3124,0.2500,-0.0938,0.1562,0.3124,0.3124,0.2188,-0.2500,'3'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7792,-0.6842,-0.3280,-0.1984,0.2956,0.8786,0.8948,0.3118,0.1822,0.1012,0.1740,...,0.7738,0.7738,0.7142,0.6428,0.5952,0.5714,0.3928,0.4286,0.2858,'24'
7793,-0.5912,-0.2420,0.8174,1.0000,0.4642,0.6428,0.6944,0.3056,-0.3888,-0.6826,...,0.1924,-0.1154,0.0192,0.2116,-0.0384,0.0192,-0.2308,-0.4230,-0.7116,'25'
7794,-0.6696,-0.3730,0.1584,0.8910,1.0000,0.9762,0.9762,0.7684,0.4106,0.0154,...,0.0910,0.1818,0.2000,0.1454,0.0182,-0.2910,0.0728,0.0728,-0.5818,'25'
7795,-0.5764,-0.1764,0.5106,0.3742,-0.1670,-0.5858,-0.7882,-0.7224,-0.6330,-0.8212,...,0.4130,0.5870,0.4348,0.5652,0.3478,-0.0434,0.3044,-0.0434,-0.5000,'26'
7796,-0.6624,-0.3334,0.3666,0.4292,-0.2084,-0.5374,-0.4542,-0.6208,-0.6376,-0.5042,...,0.2520,0.2846,0.4146,0.3170,0.2520,-0.0244,-0.0894,-0.1708,-0.3170,'26'

In [8]:
duplicate=df[df.duplicated()]
print(duplicate)

Empty DataFrame
Columns: [f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20, f21, f22, f23, f24, f25, f26, f27, f28, f29, f30, f31, f32, f33, f34, f35, f36, f37, f38, f39, f40, f41, f42, f43, f44, f45, f46, f47, f48, f49, f50, f51, f52, f53, f54, f55, f56, f57, f58, f59, f60, f61, f62, f63, f64, f65, f66, f67, f68, f69, f70, f71, f72, f73, f74, f75, f76, f77, f78, f79, f80, f81, f82, f83, f84, f85, f86, f87, f88, f89, f90, f91, f92, f93, f94, f95, f96, f97, f98, f99, f100, ...]
Index: []

[0 rows x 618 columns]

In [10]:
import numpy as np
import pandas as pd

# Example data
data = pd.read_csv("numeric.csv")

# Separate features and class label
features = data.iloc[:, :-1].apply(pd.to_numeric, errors='coerce')
class_label = data.iloc[:, -1]

# 1. Handling missing values
def handle_missing_values(features):
    # Calculate column-wise means excluding NaN values
    column_means = {}
    for column in features:
        values = [float(value) for value in features[column] if not pd.isna(value)]
        if values:
            column_means[column] = np.mean(values)
        else:
            # If all values in the column are NaN, fill with 0
            column_means[column] = 0

    # Replace NaN values with the mean of the respective column
    for column in features:
        features[column].fillna(column_means[column], inplace=True)
   
    return features

# 2. Remove duplicates
def remove_duplicates(features):
    # Check for duplicates
    if features.duplicated().any():
        print("Duplicates found and will be removed.")
        features = features.drop_duplicates()
    else:
        print("No duplicates found.")
    return features

# Apply handling missing values
features = handle_missing_values(features)
print("Data after handling missing values:")
print(features)

# Apply duplicate removal
features = remove_duplicates(features)
print("Data after removing duplicates:")
print(features)

# Also remove the corresponding rows from the class label
class_label_no_duplicates = class_label.loc[features.index]

# Reattach the class label
final_data = pd.concat([features, class_label_no_duplicates.reset_index(drop=True)], axis=1)
print("Final data with class label:")
print(final_data)

C:\Users\User\AppData\Local\Temp/ipykernel_8980/3882386238.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  features[column].fillna(column_means[column], inplace=True)

Data after handling missing values:
          f1      f2        f3      f4      f5       f6      f7      f8  \
0    -0.4394 -0.0930  0.171800  0.4620  0.6226  0.47040  0.3578  0.0478
1    -0.4348 -0.1198  0.247400  0.4036  0.5026  0.63280  0.4948  0.0338
2    -0.2330  0.2124  0.347364  0.5222 -0.3422 -0.58400 -0.7168 -0.6342
3    -0.3808 -0.0096  0.260200  0.2554 -0.4290 -0.67460 -0.6868 -0.6650
4    -0.3412  0.0946  0.608200  0.6216 -0.1622  0.16366 -0.4324 -0.4358
...      ...     ...       ...     ...     ...      ...     ...     ...
7792 -0.6842 -0.3280 -0.198400  0.2956  0.8786  0.89480  0.3118  0.1822
7793 -0.5912 -0.2420  0.817400  1.0000  0.4642  0.64280  0.6944  0.3056
7794 -0.6696 -0.3730  0.158400  0.8910  1.0000  0.97620  0.9762  0.7684
7795 -0.5764 -0.1764  0.510600  0.3742 -0.1670 -0.58580 -0.7882 -0.7224
7796 -0.6624 -0.3334  0.366600  0.4292 -0.2084 -0.53740 -0.4542 -0.6208

          f9     f10  ...    f608    f609    f610    f611    f612    f613  \
0    -0.1184 -0.2310  ...  0.3334  0.4102  0.2052  0.3846  0.3590  0.5898
1    -0.0520 -0.1302  ...  0.2272  0.0000  0.2954  0.2046  0.4772  0.0454
2    -0.8614 -0.8318  ...  0.0952 -0.1112 -0.0476 -0.1746  0.0318 -0.0476
3    -0.8410 -0.9614  ...  0.0648 -0.0504 -0.0360 -0.1224  0.1366  0.2950
4    -0.4966 -0.5406  ...  0.2812  0.1562  0.3124  0.2500 -0.0938  0.1562
...      ...     ...  ...     ...     ...     ...     ...     ...     ...
7792  0.1012  0.1740  ...  0.8928  0.7738  0.7738  0.7142  0.6428  0.5952
7793 -0.3888 -0.6826  ...  0.0192  0.1924 -0.1154  0.0192  0.2116 -0.0384
7794  0.4106  0.0154  ...  0.0000  0.0910  0.1818  0.2000  0.1454  0.0182
7795 -0.6330 -0.8212  ...  0.3044  0.4130  0.5870  0.4348  0.5652  0.3478
7796 -0.6376 -0.5042  ...  0.1056  0.2520  0.2846  0.4146  0.3170  0.2520

        f614    f615    f616    f617
0     0.3334  0.6410  0.5898 -0.4872
1     0.2046  0.4318  0.4546 -0.0910
2     0.1112  0.2540  0.1588 -0.4762
3     0.0792 -0.0072  0.0936 -0.1510
4     0.3124  0.3124  0.2188 -0.2500
...      ...     ...     ...     ...
7792  0.5714  0.3928  0.4286  0.2858
7793  0.0192 -0.2308 -0.4230 -0.7116
7794 -0.2910  0.0728  0.0728 -0.5818
7795 -0.0434  0.3044 -0.0434 -0.5000
7796 -0.0244 -0.0894 -0.1708 -0.3170

[7797 rows x 617 columns]
No duplicates found.
Data after removing duplicates:
          f1      f2        f3      f4      f5       f6      f7      f8  \
0    -0.4394 -0.0930  0.171800  0.4620  0.6226  0.47040  0.3578  0.0478
1    -0.4348 -0.1198  0.247400  0.4036  0.5026  0.63280  0.4948  0.0338
2    -0.2330  0.2124  0.347364  0.5222 -0.3422 -0.58400 -0.7168 -0.6342
3    -0.3808 -0.0096  0.260200  0.2554 -0.4290 -0.67460 -0.6868 -0.6650
4    -0.3412  0.0946  0.608200  0.6216 -0.1622  0.16366 -0.4324 -0.4358
...      ...     ...       ...     ...     ...      ...     ...     ...
7792 -0.6842 -0.3280 -0.198400  0.2956  0.8786  0.89480  0.3118  0.1822
7793 -0.5912 -0.2420  0.817400  1.0000  0.4642  0.64280  0.6944  0.3056
7794 -0.6696 -0.3730  0.158400  0.8910  1.0000  0.97620  0.9762  0.7684
7795 -0.5764 -0.1764  0.510600  0.3742 -0.1670 -0.58580 -0.7882 -0.7224
7796 -0.6624 -0.3334  0.366600  0.4292 -0.2084 -0.53740 -0.4542 -0.6208

          f9     f10  ...    f608    f609    f610    f611    f612    f613  \
0    -0.1184 -0.2310  ...  0.3334  0.4102  0.2052  0.3846  0.3590  0.5898
1    -0.0520 -0.1302  ...  0.2272  0.0000  0.2954  0.2046  0.4772  0.0454
2    -0.8614 -0.8318  ...  0.0952 -0.1112 -0.0476 -0.1746  0.0318 -0.0476
3    -0.8410 -0.9614  ...  0.0648 -0.0504 -0.0360 -0.1224  0.1366  0.2950
4    -0.4966 -0.5406  ...  0.2812  0.1562  0.3124  0.2500 -0.0938  0.1562
...      ...     ...  ...     ...     ...     ...     ...     ...     ...
7792  0.1012  0.1740  ...  0.8928  0.7738  0.7738  0.7142  0.6428  0.5952
7793 -0.3888 -0.6826  ...  0.0192  0.1924 -0.1154  0.0192  0.2116 -0.0384
7794  0.4106  0.0154  ...  0.0000  0.0910  0.1818  0.2000  0.1454  0.0182
7795 -0.6330 -0.8212  ...  0.3044  0.4130  0.5870  0.4348  0.5652  0.3478
7796 -0.6376 -0.5042  ...  0.1056  0.2520  0.2846  0.4146  0.3170  0.2520

        f614    f615    f616    f617
0     0.3334  0.6410  0.5898 -0.4872
1     0.2046  0.4318  0.4546 -0.0910
2     0.1112  0.2540  0.1588 -0.4762
3     0.0792 -0.0072  0.0936 -0.1510
4     0.3124  0.3124  0.2188 -0.2500
...      ...     ...     ...     ...
7792  0.5714  0.3928  0.4286  0.2858
7793  0.0192 -0.2308 -0.4230 -0.7116
7794 -0.2910  0.0728  0.0728 -0.5818
7795 -0.0434  0.3044 -0.0434 -0.5000
7796 -0.0244 -0.0894 -0.1708 -0.3170

[7797 rows x 617 columns]
Final data with class label:
          f1      f2        f3      f4      f5       f6      f7      f8  \
0    -0.4394 -0.0930  0.171800  0.4620  0.6226  0.47040  0.3578  0.0478
1    -0.4348 -0.1198  0.247400  0.4036  0.5026  0.63280  0.4948  0.0338
2    -0.2330  0.2124  0.347364  0.5222 -0.3422 -0.58400 -0.7168 -0.6342
3    -0.3808 -0.0096  0.260200  0.2554 -0.4290 -0.67460 -0.6868 -0.6650
4    -0.3412  0.0946  0.608200  0.6216 -0.1622  0.16366 -0.4324 -0.4358
...      ...     ...       ...     ...     ...      ...     ...     ...
7792 -0.6842 -0.3280 -0.198400  0.2956  0.8786  0.89480  0.3118  0.1822
7793 -0.5912 -0.2420  0.817400  1.0000  0.4642  0.64280  0.6944  0.3056
7794 -0.6696 -0.3730  0.158400  0.8910  1.0000  0.97620  0.9762  0.7684
7795 -0.5764 -0.1764  0.510600  0.3742 -0.1670 -0.58580 -0.7882 -0.7224
7796 -0.6624 -0.3334  0.366600  0.4292 -0.2084 -0.53740 -0.4542 -0.6208

          f9     f10  ...    f609    f610    f611    f612    f613    f614  \
0    -0.1184 -0.2310  ...  0.4102  0.2052  0.3846  0.3590  0.5898  0.3334
1    -0.0520 -0.1302  ...  0.0000  0.2954  0.2046  0.4772  0.0454  0.2046
2    -0.8614 -0.8318  ... -0.1112 -0.0476 -0.1746  0.0318 -0.0476  0.1112
3    -0.8410 -0.9614  ... -0.0504 -0.0360 -0.1224  0.1366  0.2950  0.0792
4    -0.4966 -0.5406  ...  0.1562  0.3124  0.2500 -0.0938  0.1562  0.3124
...      ...     ...  ...     ...     ...     ...     ...     ...     ...
7792  0.1012  0.1740  ...  0.7738  0.7738  0.7142  0.6428  0.5952  0.5714
7793 -0.3888 -0.6826  ...  0.1924 -0.1154  0.0192  0.2116 -0.0384  0.0192
7794  0.4106  0.0154  ...  0.0910  0.1818  0.2000  0.1454  0.0182 -0.2910
7795 -0.6330 -0.8212  ...  0.4130  0.5870  0.4348  0.5652  0.3478 -0.0434
7796 -0.6376 -0.5042  ...  0.2520  0.2846  0.4146  0.3170  0.2520 -0.0244

        f615    f616    f617  class
0     0.6410  0.5898 -0.4872    '1'
1     0.4318  0.4546 -0.0910    '1'
2     0.2540  0.1588 -0.4762    '2'
3    -0.0072  0.0936 -0.1510    '2'
4     0.3124  0.2188 -0.2500    '3'
...      ...     ...     ...    ...
7792  0.3928  0.4286  0.2858   '24'
7793 -0.2308 -0.4230 -0.7116   '25'
7794  0.0728  0.0728 -0.5818   '25'
7795  0.3044 -0.0434 -0.5000   '26'
7796 -0.0894 -0.1708 -0.3170   '26'

[7797 rows x 618 columns]